embedding:
    azure_api_key: "ec84987dfa91476889f9982dae0d7a05"
    azure_endpoint: "https://gpt4o-mini-test-us.openai.azure.com"
    azure_deployment: "text-embedding-3-large"
    azure_api_version: "2023-05-15"

chat:
    azure_api_key: "hes2jr6WSiZd86a9YAD4AIsKI59yPNwck7XbeqYnh0ByBmPRCzBXJQQJ99ALAC5T7U2XJ3w3AAABACOGeeWN"
    azure_endpoint: "https://amse-training.openai.azure.com"
    azure_deployment: "gpt-4o"
    azure_api_version: "2024-08-01-preview"
